### ISSUE TITLE
Documentation | Button

### ISSUE THREAD

**Issue by BAL4-R** [trimble-oss/modus-mobile-maui-components#107]
Create documentation for TMButton control

**Comment by rthanga1** [comment]
- Separate repo is created for the documentation (https://github.com/trimble-oss/website-modus-mobile-components.trimble.com)
- CI/CD is configured for the repo with the help of Christian Oliff
- Every commit to that repo will deply the static website in azure (https://happy-pond-034b3b40f.3.azurestaticapps.net/)
- Button documentation (https://github.com/trimble-oss/website-modus-mobile-components.trimble.com/blob/main/content/components/buttons.md)
