### ISSUE TITLE
Rough release date?

### ISSUE THREAD

**Issue by JRosanowski** [trimble-oss/modus-mobile-maui-components#169]
Hi guys, we're interested in using the library in the Trimble TerraFlex project when we migrate to Maui which we expect to start in the next couple of months. Do you have a rough time frame for a release?

Cheers,
Jonathan

**Comment by rthanga1** [comment]
Hello @JRosanowski ,
We are hoping to finish all the controls before the end of September. 

But you don't have to wait until we release all the controls. We are already working on creating the nuget package and releasing the controls we have finished so far. You can start using them by the mid of next month. We will send a internal mail once we are ready.

We have currently completed 40% of the controls which includes the following:
- Inputs
- Buttons
- Toasts
- Modals
- Cards
- Checkboxes
- Radio Buttons
- Input - Text Area
- Input - Stepper
- Segmented Controls
- Spinners

**Comment by JRosanowski** [comment]
Nice work! Thanks.
