### ISSUE TITLE
Number Input | Should update the error label when user enters invalid value

### ISSUE THREAD

**Issue by rthanga1** [trimble-oss/modus-mobile-maui-components#196]
https://docs.google.com/document/d/1I2fQGclNEcWcSL0OkBuJwfd9lIMqgFuoIXKFkSNuI-E/edit#heading=h.a5zsrup932im

**Comment by ElishaSamPeterPrabhu** [comment]
When entering a value greater than the maximum value, the value automatically sets to the maximum value and similar behavior when entering a value less than the minimum value, the value automatically sets to the minimum value.
