### ISSUE TITLE
Details of nuget & internal email group

### ISSUE THREAD

**Issue by JRosanowski** [trimble-oss/modus-mobile-maui-components#218]
I see this project has been published to nuget. How do we access it?
https://github.com/trimble-oss/modus-mobile-maui-components/issues/41

Also there's some mention of emails on an internal group. How do we join the group?

Thanks!

**Comment by rthanga1** [comment]
Hello Jonathan, 

We have finished 70% of the controls so far. We are working on the remaning few and we are also creating the documentation as of now.

The nuget package is published and it is beta now. But you can give it a try. Another team has already started using it.
You can find the development documentation (Work in progress) here
https://happy-pond-034b3b40f.3.azurestaticapps.net/getting-started/introduction/

**Comment by rthanga1** [comment]
I will send you the internal email group link in chat
https://groups.google.com/a/trimble.com/g/modus-mobile-contributors-ug

**Comment by rthanga1** [comment]
@JRosanowski I believe the information I posted above is useful to you and answers your question. I have also added you to the internal group. I am closing the ticket.
If there's anything else, please re-open this ticket.
