### ISSUE TITLE
Windows: Catastrophic failure (0x8000FFFF (E_UNEXPECTED))

### ISSUE THREAD

**Issue by JRosanowski** [trimble-oss/modus-mobile-maui-components#251]
I'm getting this exception using the Windows 0.1.0-beta
_Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled._
I've removed all Trimble Modus controls and just calling UseTrimbleModus() seems to cause the crash later on at startup (i.e. NOT in the UseTrimbleModus call). If I comment out the UseTrimbleModus() there's no crash.
 If I go back to 0.0.7-alpha I have no problem running the app with all modus controls I'm using.
Any ideas?

**Comment by ElishaSamPeterPrabhu** [comment]
fixed in the 0.1.1-beta update
contact us if any issue comes up @JRosanowski
