### ISSUE TITLE
TMButton should have a Text property to be compatible with regular MAUI button

### ISSUE THREAD

**Issue by gbriggs-trmb** [trimble-oss/modus-mobile-maui-components#252]
As a developer with existing code using Maui Button with the Text property, I would like Modus TMButton to have a Text property so I don't have to change as much code if I want to use the Modus button.

If I want to quickly refactor my app, I would like to change <Button ..../> to <modus:TMButton .../> without having to change any of the other attributes in the xaml.  

There should be a Text property for the button title so it is reverse compatible with regular button.

**Comment by rthanga1** [comment]
@gbriggs-trmb Thank you for your suggestion. We feel that it makes sense to implement this. We have refactored the property name from 'Title' to 'Text' as you suggested and we will include this with our next release (around next week)

**Comment by ElishaSamPeterPrabhu** [comment]
fixed in the 0.1.1-beta update
contact us if any issue comes up @gbriggs-trmb
