### ISSUE TITLE
Customize the Modus Controls

### ISSUE THREAD

**Issue by karthikeyanthangaraju** [trimble-oss/modus-mobile-maui-components#256]
The UI/UX design for our project differs slightly from the modus framework. We need to make additional customizations on top of the MAUI - Modus control library. At the moment, we are unable to modify the color, corner radius, and other aspects. Having this customization option would be very useful.
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/126872854/ba7dd99e-8c7f-4bf0-95cb-6a57db11897e)

![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/126872854/5062d3d0-a3d7-419a-a4b0-8ce477f855d8)

![Uploading image.png…]()

**Comment by amosekr** [comment]
I am from Groundworks Project, our project UI design is also differ from Modus framework. We unable to do the customization. It will be great if you provide a customization for the Modus controls
![Capture](https://github.com/trimble-oss/modus-mobile-maui-components/assets/152365271/0cd82168-455f-4a2c-9b04-450bbef223eb)
![Capture2](https://github.com/trimble-oss/modus-mobile-maui-components/assets/152365271/820c1b35-faff-4cda-8a1b-584b45e13899)
![Capture3](https://github.com/trimble-oss/modus-mobile-maui-components/assets/152365271/6579b91b-f340-49c5-bae2-dacad7806cb1)
