### ISSUE TITLE
Input field with units

### ISSUE THREAD

**Issue by daniel-colvin** [trimble-oss/modus-mobile-maui-components#257]
Our MAUI app has a specialized text input field that includes units (e.g. m, cm, km, miles, etc.). We use this for things like distance entry. It would be nice to have an input field with a units property, such that the units text shows to the left or the right of the user input, much like the LeftIcon/RightIcon do in TMInput.

![input with units](https://github.com/trimble-oss/modus-mobile-maui-components/assets/109182466/af9938e3-fde1-41d0-86fe-7df76a7238aa)

**Comment by rthanga1** [comment]
@daniel-colvin Thank you for creating this ticket. We are taking this back to the UX team. I will get back to you on this Friday

**Comment by ElishaSamPeterPrabhu** [comment]
@daniel-colvin This issue is fixed in the latest 0.1.2 version
