### ISSUE TITLE
DataGrid | Header UI Changes

### ISSUE THREAD

**Issue by BAL4-R** [trimble-oss/modus-mobile-maui-components#262]
Proposed changes:
- Header Text can be bold
- Header text color should be in blue color when the grid is sorted using that column

Screenshot for reference:
<img width="559" alt="Screenshot 2023-09-28 at 1 04 58 PM" src="https://github.com/trimble-oss/modus-mobile-maui-components/assets/130034598/3eca62ab-37d5-4828-93b5-444febffc800">

**Comment by rthanga1** [comment]
Make the title as semibold
