### ISSUE TITLE
Crash on Windows with 0.1.1-beta

### ISSUE THREAD

**Issue by JRosanowski** [trimble-oss/modus-mobile-maui-components#266]
Android is fine but I still seem to be getting a crash on Windows. I'm using Visual Studio 17.7.4. I've attached a sample app. Can someone try it out? Maybe I'm doing something wrong?
[ModusTestApp.zip](https://github.com/trimble-oss/modus-mobile-maui-components/files/12835102/ModusTestApp.zip)

**Comment by ElishaSamPeterPrabhu** [comment]
![VisualStudio](https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/06bf5dfa-8786-4673-8aef-009572074076)

https://github.com/trimble-oss/modus-mobile-maui-components/assets/122255626/24e1a9a8-8860-4fb6-a3f6-2f167111086a
@JRosanowski Tried your demo app its working i tried it in Visual Studio Code 2022 - Version 17.7.4 ,Can you share the crash logs?

**Comment by JRosanowski** [comment]
Which crash logs do you want?

![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/14955434/a3e5df43-57d1-467e-9743-f77522dc79bc)

**Comment by JRosanowski** [comment]
◢ | $exception | {"GenericArguments[1], 'System.Object', on 'Microsoft.Maui.Handlers.ViewHandler`2[TVirtualView,TPlatformView]' violates the constraint of type parameter 'TPlatformView'.":""} | System.TypeLoadException




  | StackTrace | "   at Trimble.Modus.Components.Handlers.LabelHandler.UpdateMaxLines(LabelHandler handler, ILabel label)\r\n   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2.<AppendToMapping>b__0(TViewHandler handler, TVirtualView view, Action`2 action)" | string

 	
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapperExtensions.AppendToMapping.AnonymousMethod__0(System.__Canon handler, System.__Canon view, System.Action<Microsoft.Maui.IElementHandler, Microsoft.Maui.IElement> action)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapperExtensions.ModifyMapping.__newMethod|0(System.__Canon handler, System.__Canon view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.Controls.Label, Microsoft.Maui.Handlers.LabelHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToPlatform(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToPlatform(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.BorderHandler.UpdateContent(Microsoft.Maui.Handlers.IBorderHandler handler)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.BorderHandler.MapContent(Microsoft.Maui.Handlers.IBorderHandler handler, Microsoft.Maui.IBorderView border)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.IBorderView, Microsoft.Maui.Handlers.IBorderHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.BorderHandler.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToPlatform(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(Microsoft.Maui.Handlers.IContentViewHandler handler)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ContentViewHandler.MapContent(Microsoft.Maui.Handlers.IContentViewHandler handler, Microsoft.Maui.IContentView page)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.IContentView, Microsoft.Maui.Handlers.IContentViewHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToPlatform(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(Microsoft.Maui.Handlers.IContentViewHandler handler)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ContentViewHandler.MapContent(Microsoft.Maui.Handlers.IContentViewHandler handler, Microsoft.Maui.IContentView page)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.IContentView, Microsoft.Maui.Handlers.IContentViewHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToPlatform(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.StackNavigationManager.OnNavigated(object sender, Microsoft.UI.Xaml.Navigation.NavigationEventArgs e)	Unknown
 	Microsoft.WinUI.dll!WinRT._EventSource_global__Microsoft_UI_Xaml_Navigation_NavigatedEventHandler.EventState.GetEventInvoke.AnonymousMethod__1_0(object sender, Microsoft.UI.Xaml.Navigation.NavigationEventArgs e)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Navigation.NavigatedEventHandler.Do_Abi_Invoke(nint thisPtr, nint sender, nint e)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(WinRT.IObjectReference _obj, System.Type sourcePageType, object parameter, Microsoft.UI.Xaml.Media.Animation.NavigationTransitionInfo infoOverride)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Controls.Frame.Navigate(System.Type sourcePageType, object parameter, Microsoft.UI.Xaml.Media.Animation.NavigationTransitionInfo infoOverride)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.StackNavigationManager.NavigateTo(Microsoft.Maui.NavigationRequest args)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellSectionHandler.RequestNavigation(Microsoft.Maui.Controls.Handlers.ShellSectionHandler handler, Microsoft.Maui.IStackNavigation view, object arg3)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.CommandMapper<Microsoft.Maui.Controls.ShellSection, Microsoft.Maui.Controls.Handlers.ShellSectionHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v, object o)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.CommandMapper.InvokeCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView, object args)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.CommandMapper.Invoke(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView, string property, object args)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.Invoke(string command, object args)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.ShellSection.Microsoft.Maui.IStackNavigation.RequestNavigation(Microsoft.Maui.NavigationRequest eventArgs)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SyncNavigationStack(bool animated, Microsoft.Maui.Controls.Internals.NavigationRequestedEventArgs e)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellSectionHandler.MapCurrentItem(Microsoft.Maui.Controls.Handlers.ShellSectionHandler handler, Microsoft.Maui.Controls.ShellSection item)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.Controls.ShellSection, Microsoft.Maui.Controls.Handlers.ShellSectionHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellItemHandler.UpdateCurrentItem()	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellItemHandler.MapCurrentItem(Microsoft.Maui.Controls.Handlers.ShellItemHandler handler, Microsoft.Maui.Controls.ShellItem item)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.Controls.ShellItem, Microsoft.Maui.Controls.Handlers.ShellItemHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellItemHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Platform.ShellView.CreateShellItemView()	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Platform.ShellView.SwitchShellItem(Microsoft.Maui.Controls.ShellItem newItem, bool animate)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellHandler.MapCurrentItem(Microsoft.Maui.Controls.Handlers.ShellHandler handler, Microsoft.Maui.Controls.Shell view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.Controls.Shell, Microsoft.Maui.Controls.Handlers.ShellHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Handlers.ShellHandler.SetVirtualView(Microsoft.Maui.IView view)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ViewHandler<System.__Canon, System.__Canon>.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToHandler(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.ToPlatform(Microsoft.Maui.IElement view, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.WindowHandler.MapContent(Microsoft.Maui.Handlers.IWindowHandler handler, Microsoft.Maui.IWindow window)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper<Microsoft.Maui.IWindow, Microsoft.Maui.Handlers.IWindowHandler>.Add.AnonymousMethod__0(Microsoft.Maui.IElementHandler h, Microsoft.Maui.IElement v)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdatePropertyCore(string key, Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.PropertyMapper.UpdateProperties(Microsoft.Maui.IElementHandler viewHandler, Microsoft.Maui.IElement virtualView)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(Microsoft.Maui.IElement view)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.SetHandler(Microsoft.Maui.IElementHandler newHandler)	Unknown
 	Microsoft.Maui.Controls.dll!Microsoft.Maui.Controls.Element.Handler.set(Microsoft.Maui.IElementHandler value)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.SetHandler(WinRT.IWinRTObject nativeElement, Microsoft.Maui.IElement element, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(Microsoft.UI.Xaml.Window platformWindow, Microsoft.Maui.IWindow window, Microsoft.Maui.IMauiContext context)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Microsoft.UI.Xaml.Application platformApplication, Microsoft.Maui.IApplication application, Microsoft.Maui.Handlers.OpenWindowRequest args)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Microsoft.UI.Xaml.Application platformApplication, Microsoft.Maui.IApplication application, Microsoft.UI.Xaml.LaunchActivatedEventArgs args)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.MauiWinUIApplication.OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(nint thisPtr, nint args)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
>	ModusTestApp.dll!ModusTestApp.WinUI.Program.Main(string[] args) Line 31	C#

**Comment by ElishaSamPeterPrabhu** [comment]
> Which crash logs do you want?
> 
> ![image](https://user-images.githubusercontent.com/14955434/273829963-a3e5df43-57d1-467e-9743-f77522dc79bc.png)

Seems like the similar error we had last release
but as per the video am unable to reproduce it ,
Can you check the version is updated?maybe remove the nuget package and add it again. @JRosanowski

**Comment by JRosanowski** [comment]
It looks like the correct dll in the bin directory

![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/14955434/62096a87-7818-49d0-a3b8-95fb6c5add0f)

**Comment by JRosanowski** [comment]
Both of my colleagues are seeing the same crash with the attached project.

**Comment by JRosanowski** [comment]
It looks like something to do with the code that gets generated in the LabelHandler UpdateMaxLines.
In the decompiled Trimble Modus nuget dll the Windows code is

```
private static void UpdateMaxLines(Microsoft.Maui.Handlers.LabelHandler handler, ILabel label)
{
  object platformView = ((ViewHandler<ILabel, object>) handler).PlatformView;
  Label label1 = label as Label;
}
```

If you put ViewHandler<ILabel, object> into the Modus demo project in any of the Platforms it will complain about object violating the TPlatformView constraint - same as the exception that's being thrown.

If I create a nuget from the Trimble Modus source then the Windows code looks like this.

```
private static void UpdateMaxLines(Microsoft.Maui.Handlers.LabelHandler handler, ILabel label)
{
   TextBlock platformView = handler.PlatformView;
   Label label1 = label as Label;
}
```

**Comment by JRosanowski** [comment]
No longer a problem in 0.1.2 Beta

**Comment by ElishaSamPeterPrabhu** [comment]
Thanks, @JRosanowski 

> No longer a problem in 0.1.2 Beta
