### ISSUE TITLE
Progress Bars

### ISSUE THREAD

**Issue by rthanga1** [trimble-oss/modus-mobile-maui-components#30]
Overview:
Inform users about the status of ongoing processes
Doc:
https://modus.trimble.com/components/mobile/progress-bars/

Spec:
- Size (Default/Small)
- Indicator text

 - Create a wrapper and add the MAUI's progress bar and a indicator label
 - Check if we can customize the appearance of the MAUI progress bar (particularly the fill color rounded border)
 - Export ProgressTo method and OnProgressChanged event handler (and command), progress property

**Comment by Sofiya-kumar** [comment]
Implemented Progress bar with indicator text
