### ISSUE TITLE
The first tab view is not displaying in TabbedPage in Windows

### ISSUE THREAD

**Issue by amosekr** [trimble-oss/modus-mobile-maui-components#350]
The selected location tabview is not appearing, the current page belongs to Pass/Fail tabview.
![image](https://github.com/trimble-oss/modus-mobile-maui-components/assets/152365271/32fb8734-1ad9-4672-999c-5447a9c5a456)

The issue is first tab view is not appearing, even if i switched to other tabs and come back to first tab, then also first tab view is not appearing for windows alone

**Comment by Sofiya-kumar** [comment]
https://github.com/dotnet/maui/issues/18334

With default Maui TabbedPage we don't have enough options to customise the UI. 

So we used CarouselView to achieve the tabbed page. But in the windows, CarouselView has an open issue, the first item is not displaying.
