### ISSUE TITLE
Add README, CONTRIBUTING and LICENSE .md files

### ISSUE THREAD

**Issue by BAL4-R** [trimble-oss/modus-mobile-maui-components#46]
Add following files to the project

- README.md
- CONTRIBUTING.md
- LICENSE.md

**Comment by rthanga1** [comment]
Refer the Modus web components project
[ReadMe](https://github.com/trimble-oss/modus-web-components/blob/main/README.md)
[LICENSE](https://github.com/trimble-oss/modus-web-components/blob/main/LICENSE)
[CONTRIBUTING](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

- Link the [Developer documentation](https://happy-pond-034b3b40f.3.azurestaticapps.net/) in the read me file
- In the contributing file, add getting started, developer setup (like link to install git, vs, github desktop...), instructions to run demo app
- Copy the Submitting Issues section as it is
-

**Comment by rthanga1** [comment]
- Add ChangeLog section -> Attach our drive link
- Have a query -> Give our group email ID
